# Generated by Django 4.2.4 on 2023-09-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
