# Generated by Django 4.2.4 on 2023-09-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='temp',
            new_name='temperature',
        ),
    ]
